from string import ascii_lowercase, ascii_uppercase

import nle.nethack.actions as A

# Mapping from string name to NLE Action Enum
PRIMITIVE_ACTION_MAP = {
    "help": A.UnsafeActions.HELP,
    "previous message": A.UnsafeActions.PREVMSG,
    "north": A.CompassDirection.N,
    "east": A.CompassDirection.E,
    "south": A.CompassDirection.S,
    "west": A.CompassDirection.W,
    "northeast": A.CompassIntercardinalDirection.NE,
    "southeast": A.CompassIntercardinalDirection.SE,
    "southwest": A.CompassIntercardinalDirection.SW,
    "northwest": A.CompassIntercardinalDirection.NW,
    "far north": A.CompassCardinalDirectionLonger.N,
    "far east": A.CompassCardinalDirectionLonger.E,
    "far south": A.CompassCardinalDirectionLonger.S,
    "far west": A.CompassCardinalDirectionLonger.W,
    "far northeast": A.CompassIntercardinalDirectionLonger.NE,
    "far southeast": A.CompassIntercardinalDirectionLonger.SE,
    "far southwest": A.CompassIntercardinalDirectionLonger.SW,
    "far northwest": A.CompassIntercardinalDirectionLonger.NW,
    "up": A.MiscDirection.UP,
    "down": A.MiscDirection.DOWN,
    "wait": A.MiscDirection.WAIT,
    "more": A.MiscAction.MORE,
    "extcmd": A.Command.EXTCMD,
    "extlist": A.Command.EXTLIST,
    "adjust": A.Command.ADJUST,
    "annotate": A.Command.ANNOTATE,
    "apply": A.Command.APPLY,
    "attributes": A.Command.ATTRIBUTES,
    "autopickup": A.Command.AUTOPICKUP,
    "call": A.Command.CALL,
    "cast": A.Command.CAST,
    "chat": A.Command.CHAT,
    "close": A.Command.CLOSE,
    "conduct": A.Command.CONDUCT,
    "dip": A.Command.DIP,
    "drop": A.Command.DROP,
    "droptype": A.Command.DROPTYPE,
    "eat": A.Command.EAT,
    "esc": A.Command.ESC,
    "engrave": A.Command.ENGRAVE,
    "enhance": A.Command.ENHANCE,
    "fire": A.Command.FIRE,
    "fight": A.Command.FIGHT,
    "force": A.Command.FORCE,
    "glance": A.Command.GLANCE,
    "history": A.Command.HISTORY,
    "inventory": A.Command.INVENTORY,
    "inventtype": A.Command.INVENTTYPE,
    "invoke": A.Command.INVOKE,
    "jump": A.Command.JUMP,
    "kick": A.Command.KICK,
    "known": A.Command.KNOWN,
    "knownclass": A.Command.KNOWNCLASS,
    "look": A.Command.LOOK,
    "loot": A.Command.LOOT,
    "monster": A.Command.MONSTER,
    "move": A.Command.MOVE,
    "movefar": A.Command.MOVEFAR,
    "offer": A.Command.OFFER,
    "open": A.Command.OPEN,
    "options": A.Command.OPTIONS,
    "overview": A.Command.OVERVIEW,
    "pay": A.Command.PAY,
    "pickup": A.Command.PICKUP,
    "pray": A.Command.PRAY,
    "puton": A.Command.PUTON,
    "quaff": A.Command.QUAFF,
    "quit": A.Command.QUIT,
    "quiver": A.Command.QUIVER,
    "read": A.Command.READ,
    "redraw": A.Command.REDRAW,
    "remove": A.Command.REMOVE,
    "ride": A.Command.RIDE,
    "rub": A.Command.RUB,
    "rush": A.Command.RUSH,
    "rush2": A.Command.RUSH2,
    "save": A.Command.SAVE,
    "search": A.Command.SEARCH,
    "seeall": A.Command.SEEALL,
    "seeamulet": A.Command.SEEAMULET,
    "seearmor": A.Command.SEEARMOR,
    "seegold": A.Command.SEEGOLD,
    "seerings": A.Command.SEERINGS,
    "seespells": A.Command.SEESPELLS,
    "seetools": A.Command.SEETOOLS,
    "seetrap": A.Command.SEETRAP,
    "seeweapon": A.Command.SEEWEAPON,
    "shell": A.Command.SHELL,
    "sit": A.Command.SIT,
    "swap": A.Command.SWAP,
    "takeoff": A.Command.TAKEOFF,
    "takeoffall": A.Command.TAKEOFFALL,
    "teleport": A.Command.TELEPORT,
    "throw": A.Command.THROW,
    "tip": A.Command.TIP,
    "travel": A.Command.TRAVEL,
    "turnundead": A.Command.TURN,
    "twoweapon": A.Command.TWOWEAPON,
    "untrap": A.Command.UNTRAP,
    "version": A.Command.VERSION,
    "versionshort": A.Command.VERSIONSHORT,
    "wear": A.Command.WEAR,
    "whatdoes": A.Command.WHATDOES,
    "whatis": A.Command.WHATIS,
    "wield": A.Command.WIELD,
    "wipe": A.Command.WIPE,
    "zap": A.Command.ZAP,
    "minus": A.TextCharacters.MINUS,
    "space": A.TextCharacters.SPACE,
    "apos": A.TextCharacters.APOS,
    "0": A.TextCharacters.NUM_0,
    "1": A.TextCharacters.NUM_1,
    "2": A.TextCharacters.NUM_2,
    "3": A.TextCharacters.NUM_3,
    "4": A.TextCharacters.NUM_4,
    "5": A.TextCharacters.NUM_5,
    "6": A.TextCharacters.NUM_6,
    "7": A.TextCharacters.NUM_7,
    "8": A.TextCharacters.NUM_8,
    "9": A.TextCharacters.NUM_9,
    "wizard detect": A.WizardCommand.WIZDETECT,
    "wizard genesis": A.WizardCommand.WIZGENESIS,
    "wizard identify": A.WizardCommand.WIZIDENTIFY,
    "wizard teleport": A.WizardCommand.WIZLEVELPORT,
    "wizard map": A.WizardCommand.WIZMAP,
    "wizard where": A.WizardCommand.WIZWHERE,
    "wizard wish": A.WizardCommand.WIZWISH,
    **{char: ord(char) for char in ascii_lowercase + ascii_uppercase}
}

PRIMITIVE_DESCRIPTIONS = {
    "north": "go one step north",
    "east": "go one step east",
    "south": "go one step south",
    "west": "go one step west",
    "northeast": "go one step northeast",
    "southeast": "go one step southeast",
    "southwest": "go one step southwest",
    "northwest": "go one step northwest",
    "far north": "go north until you hit a wall or run into something",
    "far east": "go east until you hit a wall or run into something",
    "far south": "go south until you hit a wall or run into something",
    "far west": "go west until you hit a wall or run into something",
    "far northeast": "go northeast until you hit a wall or run into something",
    "far southeast": "go southeast until you hit a wall or run into something",
    "far southwest": "go southwest until you hit a wall or run into something",
    "far northwest": "go northwest until you hit a wall or run into something",
    "up": "go up a staircase (if you are standing on it)",
    "down": "go down a staircase (if you are standing on it)",
    "wait": "rest, do nothing for one turn",
    "more": "display more of the message",
    "annotate": "leave a note about the level",
    "apply": "apply (use) a tool (pick-axe, key, lamp...)",
    "call": "name (call) a monster, individual object, or type of object",
    "cast": "cast a spell",
    "close": "close a door",
    "open": "open a door",
    "dip": "dip an object into something",
    "drop": "drop something",
    "droptype": "drop multiple items",
    "eat": "eat food",
    "esc": "exit menu or message",
    "engrave": "engrave a message on the floor",
    "enhance": "advance or check weapons skills",
    "fire": "fire ammunition from quiver",
    "fight": "fight a monster (even if you don't sense it)",
    "force": "force a lock",
    "inventory": "display your inventory",
    "invoke": "invoke an object's special powers",
    "jump": "jump to another location",
    "kick": "kick a door, chest, or enemy",
    "look": "look at what is here",
    "loot": "loot a box on the floor",
    "monster": "use a monster's special ability (when polymorphed)",
    "offer": "offer a sacrifice to the gods",
    "overview": "display an overview of the dungeon",
    "pay": "pay your shopping bill",
    "pickup": "pick up some things",
    "pray": "pray to the gods for help",
    "puton": "put on an accessory (ring, amulet, etc)",
    "quaff": "drink (quaff) something (potion, water, etc)",
    "quiver": "select ammunition for quiver",
    "read": "read a scroll or spellbook",
    "remove": "remove an accessory (ring, amulet, etc)",
    "rub": "rub a lamp or a stone",
    "search": "search for secret doors and traps around you",
    "swap": "swap wielded and secondary weapons",
    "takeoff": "take off armor",
    "takeoffall": "take off all armor",
    "teleport": "teleport, if you are able",
    "throw": "throw an object or shoot a projectile",
    "travel": "travel via a shortest-path algorithm to a point on the map",
    "twoweapon": "toggle two-weapon combat",
    "untrap": "untrap a trapped object or door",
    "wear": "wear armor",
    "wield": "wield weapon (w- means wield nothing)",
    "wipe": "wipe off your face",
    "zap": "zap a wand",
    "minus": "-",
    "space": " ",
    "apos": "'",
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "help": "show the help menu",
    "previous message": "repeat last message",
    "extcmd": "extended command (#)",
    "extlist": "list extended commands",
    "adjust": "adjust inventory letters",
    "attributes": "show your attributes",
    "autopickup": "toggle the pickup option",
    "chat": "chat with a monster",
    "conduct": "show conduct",
    "glance": "glance at a position",
    "history": "display a longer identification of the version and history",
    "inventtype": "inventory by type",
    "known": "show known items",
    "knownclass": "show known item classes",
    "move": "move without picking up objects",
    "movefar": "run in direction until something interesting is seen",
    "options": "review current options and possibly change them",
    "quit": "exit the program without saving the current game",
    "redraw": "redraw the screen",
    "ride": "ride a monster",
    "rush": "rush",
    "rush2": "rush",
    "save": "save the game and exit",
    "seeall": "see all",
    "seeamulet": "see amulet",
    "seearmor": "see armor",
    "seegold": "see gold",
    "seerings": "see rings",
    "seespells": "list the spells you know",
    "seetools": "see tools",
    "seetrap": "ask for the type of a trap you found earlier",
    "seeweapon": "tell what weapon you are wielding",
    "shell": "escape to a shell",
    "sit": "sit down",
    "tip": "empty a container",
    "turnundead": "turn undead",
    "version": "display the version number",
    "versionshort": "show short version",
    "whatdoes": "tell what a command does",
    "whatis": "tell what a symbol represents",
    "wizard detect": "wizard detect",
    "wizard genesis": "wizard genesis",
    "wizard identify": "wizard identify",
    "wizard teleport": "wizard teleport",
    "wizard map": "wizard map",
    "wizard where": "wizard where",
    "wizard wish": "wizard wish",
    **{char: f"type character '{char}'" for char in ascii_lowercase + ascii_uppercase}
}
