import nle.nethack.actions as A

# Mapping from string name to NLE Action Enum
PRIMITIVE_ACTION_MAP = {
    "help": A.UnsafeActions.HELP,
    "previous message": A.UnsafeActions.PREVMSG,
    "north": A.CompassDirection.N,
    "east": A.CompassDirection.E,
    "south": A.CompassDirection.S,
    "west": A.CompassDirection.W,
    "northeast": A.CompassIntercardinalDirection.NE,
    "southeast": A.CompassIntercardinalDirection.SE,
    "southwest": A.CompassIntercardinalDirection.SW,
    "northwest": A.CompassIntercardinalDirection.NW,
    "far north": A.CompassCardinalDirectionLonger.N,
    "far east": A.CompassCardinalDirectionLonger.E,
    "far south": A.CompassCardinalDirectionLonger.S,
    "far west": A.CompassCardinalDirectionLonger.W,
    "far northeast": A.CompassIntercardinalDirectionLonger.NE,
    "far southeast": A.CompassIntercardinalDirectionLonger.SE,
    "far southwest": A.CompassIntercardinalDirectionLonger.SW,
    "far northwest": A.CompassIntercardinalDirectionLonger.NW,
    "up": A.MiscDirection.UP,
    "down": A.MiscDirection.DOWN,
    "wait": A.MiscDirection.WAIT,
    "more": A.MiscAction.MORE,
    "extcmd": A.Command.EXTCMD,
    "extlist": A.Command.EXTLIST,
    "adjust": A.Command.ADJUST,
    "annotate": A.Command.ANNOTATE,
    "apply": A.Command.APPLY,
    "attributes": A.Command.ATTRIBUTES,
    "autopickup": A.Command.AUTOPICKUP,
    "call": A.Command.CALL,
    "cast": A.Command.CAST,
    "chat": A.Command.CHAT,
    "close": A.Command.CLOSE,
    "conduct": A.Command.CONDUCT,
    "dip": A.Command.DIP,
    "drop": A.Command.DROP,
    "droptype": A.Command.DROPTYPE,
    "eat": A.Command.EAT,
    "esc": A.Command.ESC,
    "engrave": A.Command.ENGRAVE,
    "enhance": A.Command.ENHANCE,
    "fire": A.Command.FIRE,
    "fight": A.Command.FIGHT,
    "force": A.Command.FORCE,
    "glance": A.Command.GLANCE,
    "history": A.Command.HISTORY,
    "inventory": A.Command.INVENTORY,
    "inventtype": A.Command.INVENTTYPE,
    "invoke": A.Command.INVOKE,
    "jump": A.Command.JUMP,
    "kick": A.Command.KICK,
    "known": A.Command.KNOWN,
    "knownclass": A.Command.KNOWNCLASS,
    "look": A.Command.LOOK,
    "loot": A.Command.LOOT,
    "monster": A.Command.MONSTER,
    "move": A.Command.MOVE,
    "movefar": A.Command.MOVEFAR,
    "offer": A.Command.OFFER,
    "open": A.Command.OPEN,
    "options": A.Command.OPTIONS,
    "overview": A.Command.OVERVIEW,
    "pay": A.Command.PAY,
    "pickup": A.Command.PICKUP,
    "pray": A.Command.PRAY,
    "puton": A.Command.PUTON,
    "quaff": A.Command.QUAFF,
    "quit": A.Command.QUIT,
    "quiver": A.Command.QUIVER,
    "read": A.Command.READ,
    "redraw": A.Command.REDRAW,
    "remove": A.Command.REMOVE,
    "ride": A.Command.RIDE,
    "rub": A.Command.RUB,
    "rush": A.Command.RUSH,
    "rush2": A.Command.RUSH2,
    "save": A.Command.SAVE,
    "search": A.Command.SEARCH,
    "seeall": A.Command.SEEALL,
    "seeamulet": A.Command.SEEAMULET,
    "seearmor": A.Command.SEEARMOR,
    "seegold": A.Command.SEEGOLD,
    "seerings": A.Command.SEERINGS,
    "seespells": A.Command.SEESPELLS,
    "seetools": A.Command.SEETOOLS,
    "seetrap": A.Command.SEETRAP,
    "seeweapon": A.Command.SEEWEAPON,
    "shell": A.Command.SHELL,
    "sit": A.Command.SIT,
    "swap": A.Command.SWAP,
    "takeoff": A.Command.TAKEOFF,
    "takeoffall": A.Command.TAKEOFFALL,
    "teleport": A.Command.TELEPORT,
    "throw": A.Command.THROW,
    "tip": A.Command.TIP,
    "travel": A.Command.TRAVEL,
    "turnundead": A.Command.TURN,
    "twoweapon": A.Command.TWOWEAPON,
    "untrap": A.Command.UNTRAP,
    "version": A.Command.VERSION,
    "versionshort": A.Command.VERSIONSHORT,
    "wear": A.Command.WEAR,
    "whatdoes": A.Command.WHATDOES,
    "whatis": A.Command.WHATIS,
    "wield": A.Command.WIELD,
    "wipe": A.Command.WIPE,
    "zap": A.Command.ZAP,
    "minus": A.TextCharacters.MINUS,
    "space": A.TextCharacters.SPACE,
    "apos": A.TextCharacters.APOS,
    "0": A.TextCharacters.NUM_0,
    "1": A.TextCharacters.NUM_1,
    "2": A.TextCharacters.NUM_2,
    "3": A.TextCharacters.NUM_3,
    "4": A.TextCharacters.NUM_4,
    "5": A.TextCharacters.NUM_5,
    "6": A.TextCharacters.NUM_6,
    "7": A.TextCharacters.NUM_7,
    "8": A.TextCharacters.NUM_8,
    "9": A.TextCharacters.NUM_9,
    "wizard detect": A.WizardCommand.WIZDETECT,
    "wizard genesis": A.WizardCommand.WIZGENESIS,
    "wizard identify": A.WizardCommand.WIZIDENTIFY,
    "wizard teleport": A.WizardCommand.WIZLEVELPORT,
    "wizard map": A.WizardCommand.WIZMAP,
    "wizard where": A.WizardCommand.WIZWHERE,
    "wizard wish": A.WizardCommand.WIZWISH,
}

PRIMITIVE_DESCRIPTIONS = {
    "north": "move north",
    "east": "move east",
    "south": "move south",
    "west": "move west",
    "northeast": "move northeast",
    "southeast": "move southeast",
    "southwest": "move southwest",
    "northwest": "move northwest",
    "far north": "move far north",
    "far east": "move far east",
    "far south": "move far south",
    "far west": "move far west",
    "far northeast": "move far northeast",
    "far southeast": "move far southeast",
    "far southwest": "move far southwest",
    "far northwest": "move far northwest",
    "up": "go up a staircase",
    "down": "go down a staircase (tip: you can only go down if you are standing on the stairs)",
    "wait": "rest one move while doing nothing",
    "more": "display more of the message (tip: ONLY ever use when current message ends with --More--)",
    "annotate": "leave a note about the level",
    "apply": "apply (use) a tool",
    "call": "name a monster or object, or add an annotation",
    "cast": "cast a spell",
    "close": "close an adjacent door",
    "open": "open an adjacent door",
    "dip": "dip an object into something",
    "drop": "drop an item",
    "droptype": "drop specific item types (specify in the next prompt)",
    "eat": "eat something (tip: replenish food when hungry)",
    "esc": "exit menu or message",
    "engrave": "engrave writing on the floor (tip: Elbereth)",
    "enhance": "advance or check weapons skills",
    "fire": "fire ammunition from quiver",
    "fight": "fight a monster (even if you only guess one is there)",
    "force": "force a lock",
    "inventory": "show your inventory",
    "invoke": "invoke ",
    "jump": "jump to a location",
    "kick": "kick an enemy or a locked door or chest",
    "look": "look at what is under you",
    "loot": "loot a box on the floor",
    "monster": "use a monster's special ability (when polymorphed)",
    "offer": "offer a sacrifice to the gods (tip: on an aligned altar)",
    "overview": "display an overview of the dungeon",
    "pay": "pay your shopping bill",
    "pickup": "pick up things at the current location",
    "pray": "pray to the gods for help",
    "puton": "put on an accessory",
    "quaff": "quaff (drink) something",
    "quiver": "select ammunition for quiver",
    "read": "read a scroll or spellbook",
    "remove": "remove an accessory",
    "rub": "rub a lamp or a stone",
    "search": "search for hidden doors and passages",
    "swap": "swap wielded and secondary weapons",
    "takeoff": "take off one piece of armor",
    "takeoffall": "take off all armor",
    "teleport": "teleport to another level (if you have the ability)",
    "throw": "throw something (e.g. a dagger or dart)",
    "travel": "travel to a specific location on the map (tip: in the next action, specify > or < for stairs, { for fountain, and _ for altar)",
    "twoweapon": "toggle two-weapon combat",
    "untrap": "untrap something",
    "wear": "wear a piece of armor",
    "wield": "wield a weapon",
    "wipe": "wipe off your face",
    "zap": "zap a wand",
    "minus": "-",
    "space": " ",
    "apos": "'",
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "help": "show help",
    "previous message": "show previous message",
    "extcmd": "extended command",
    "extlist": "list extended commands",
    "adjust": "adjust inventory letters",
    "attributes": "show attributes",
    "autopickup": "toggle autopickup",
    "chat": "chat with a monster",
    "conduct": "show conduct",
    "glance": "glance at a position",
    "history": "show version history",
    "inventtype": "inventory by type",
    "known": "show known items",
    "knownclass": "show known item classes",
    "move": "move to a position",
    "movefar": "move far to a position",
    "options": "show options",
    "quit": "quit the game",
    "redraw": "redraw the screen",
    "ride": "ride a monster",
    "rush": "rush",
    "rush2": "rush",
    "save": "save the game",
    "seeall": "see all",
    "seeamulet": "see amulet",
    "seearmor": "see armor",
    "seegold": "see gold",
    "seerings": "see rings",
    "seespells": "see spells",
    "seetools": "see tools",
    "seetrap": "see traps",
    "seeweapon": "see weapon",
    "shell": "shell",
    "sit": "sit down",
    "tip": "empty a container",
    "turnundead": "turn undead",
    "version": "show version",
    "versionshort": "show short version",
    "whatdoes": "what does a key do",
    "whatis": "what is a symbol",
    "wizard detect": "wizard detect",
    "wizard genesis": "wizard genesis",
    "wizard identify": "wizard identify",
    "wizard teleport": "wizard teleport",
    "wizard map": "wizard map",
    "wizard where": "wizard where",
    "wizard wish": "wizard wish",
}
